import type { Metadata } from "next";


export const metadata: Metadata = {
  title: "Tristan of Whitewood",
  description: "Generated by create next app",
    icons: ["favicon.png"]
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        {children}
      </body>
    </html>
  );
}
